name: ramcleaner
version: 1.0
description: Bukkit Plugin with Clean Memory and RAM Status Commands
main: com.example.ramcleaner.ramcleaner
author: katilmami
api-version: 1.7
website: https://github.com/Katilmami/ramcleanerplugin
commands:
  ramclean:
    description: Deep clean up memory
    usage: /ramclean
    permission: ramcleaner.ramclean
  ramstatus:
    description: Display RAM status
    usage: /ramstatus
    permission: ramcleaner.ramstatus
