name: ramcleaner
version: 1.0
description: Bukkit Plugin with Clean Memory Command
main: com.example.ramcleaner.ramcleaner
author: katilmami
api-version: 1.13
website: https://github.com/Katilmami/ramcleanerplugin
commands:
  ramclean:
    description: Deep clean up memory
    usage: /ramclean
    permission: ramcleaner.ramclean
