name: Build and Upload JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Download Dependencies and Build JAR
      run: mvn clean install

    - name: Create JAR with plugin.yml
      run: jar -cvf target/DeepCleanMemoryPlugin-1.0-SNAPSHOT.jar -C target/ .

    - name: Upload JAR to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DeepCleanMemoryPlugin
        path: target/DeepCleanMemoryPlugin-1.0-SNAPSHOT.jar
