name: Build and Upload JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Download Dependencies and Compile Java
      run: mvn clean install

    - name: Copy plugin.yml into JAR
      run: jar uf target/DeepCleanMemoryPlugin-1.0-SNAPSHOT.jar -C src/main/resources/META-INF plugin.yml

    - name: Upload JAR to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ramcleaner
        path: target/DeepCleanMemoryPlugin-1.0-SNAPSHOT.jar
