name: Build and Upload JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Download Dependencies
      run: mvn dependency:resolve
    - name: target folder create
      run: mkdir target
    - name: Compile Java
      run: javac -d target src/main/java/com/example/DeepCleanMemoryPlugin/DeepCleanMemoryPlugin.java

    - name: Create JAR
      run: jar -cvf target/ramcleaner.jar -C target/ .

    - name: Copy plugin.yml
      run: cp src/main/resources/META-INF/plugin.yml target/

    - name: Upload JAR to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ramcleaner
        path: target/ramcleaner.jar
